GET http://localhost:3000/accounts

###
GET http://localhost:3000/accounts/b39b786a-46ca-48db-b535-2d1bdc80dbb4



###
POST http://localhost:3000/accounts
Content-Type: application/json

{
    "name": "conta 1"
}

###
PATCH http://localhost:3000/accounts/bf606d72-7020-403d-a940-a9fba4bc9ce7
Content-Type: application/json

{
    "name": "conta 1 alterada"
}
