GET http://localhost:3000/orders
x-token: y1zu8o5lrj

###
GET http://localhost:3000/orders/4a55d171-c8a2-436f-bd90-56318f72f00e

###
POST http://localhost:3000/orders
Content-Type: application/json
x-token: j9l3y46lad

{
    "amount": 10.10,
    "credit_card_number":"1111",
    "credit_card_name":"Jin Bok"
}

###
PATCH http://localhost:3000/orders/4a55d171-c8a2-436f-bd90-56318f72f00e
Content-Type: application/json

{
    "amount": 30.10,
    "credit_card_number":"123456789"
}

###
DELETE http://localhost:3000/orders/4a55d171-c8a2-436f-bd90-56318f72f00e
